### ISSUE TITLE
how to justify if different experts contribute to the result?

### ISSUE THREAD

**Issue by LiFeiAStoneHood** [TsinghuaDatabaseGroup/DB-GPT#51]
from the code, the llm behinds all experts are the same(GPT-4). Have you fine-tuned each experts with different knowledge? 
how about if we provide the specific domain knowledges(IO/CPU/mem) to an agent? as GPT-4 is a good enough llm to handle such knowledge.

**Comment by zhouxh19** [comment]
Thank you for your attention. Currently, we just fine-tuned the same llm (e.g., llama2) for all the experts. From our recent evaluation, multi-expert llm works much better than single-expert llm, especially when more than one alert occurs at the same time (probably due to the finer-grained role assignment and more thorough discussion). Besides, gpt-4 is not as good as we expected in following the matched knowledge (e.g., may still give very general solutions). We will release a detailed technical report soon :)

**Comment by zhouxh19** [comment]
we do not fine-tune llm for each expert because it is too costly😰 in the future we may support dozens of expert types

**Comment by LiFeiAStoneHood** [comment]
> we do not fine-tune llm for each expert because it is too costly😰 in the future we may support dozens of expert types

thanks for the reply. it makes sense to setting up knowledge database instead of training many experts. great work!!
